### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by TheLoneUs** [jlennox/HeartRate#19]
When setting the font size directly to something like "128" it is reduced to "96" - it appears to be a percentage reduction and it's really hard to get the font size I'm trying to set.

Appears to happen for all font sizes selected via the GUI.

**Comment by jlennox** [comment]
@TheLoneUs 

Ah, I see what's happening. It's converting my pixel sizes to point's for the dialog. 
[fix-font-size-test1.zip](https://github.com/jlennox/HeartRate/files/5751886/fix-font-size-test1.zip)

Let me know if this fixes your issue.

I'm also curious why you're using manual font sizes instead of letting it scale with the window?

Thanks for the report!

**Comment by TheLoneUs** [comment]
@jlennox I am using the specific font size for consistencies sake while streaming. I figured if I set it explicitly it will be harder to accidentally mess it up, and I can set it to the size I want without resizing in OBS. My hope there is that with no resizing in OBS it will be better quality on stream.

**Comment by jlennox** [comment]
Thanks for testing and for the information! I'm glad to know the use cases.
