### ISSUE TITLE
Issue with an USB dongle

### ISSUE THREAD

**Issue by rhymak** [jlennox/HeartRate#3]
Hi!

First of all, thank you for your work, seems very useful. 
I got the heart rate monitor working on a "mini PC" with built-in bluetooth device (win10). 
However, on my desktop (which I need to use in my research), I use an USB BT receiver, which doesn't seem to work. 
I am able to pair my polar a370 watch with windows without an issue, but after running the I get one of the following 2 (seemingly at random):
1. unable to locate HR measurement on device polar a370 (link: [https://imgur.com/a/YLBjp] )
2. stuck on "starting..." - usually after restart the 1st time I try to run the exe

The BT receiver is my only BT device, no duplicate drivers or anything.
Any suggestions?

Just FYI, I plan to use the program to visualize HR data during gameplay in my dissertation research, in combination with other physiological measurements (from different sensors). I plan to draw a real-time graph of these readings in the future, feel free to ask if you're interested.

**Comment by jlennox** [comment]
I'm glad to hear some of the code maybe of wider use to you!

It appears the a370 itself is not a heart rate sensor but pairs with them: https://support.polar.com/e_manuals/A370/Polar_A370_user_manual_English/Content/Pairing.htm

There's also no mention of it on: http://developer.polar.com/wiki/H6,_H7_and_H10_Heart_rate_sensors (or that wiki at all, sadly).

The error the program is giving is indicative it couldn't find a monitor of type org.bluetooth.characteristic.heart_rate_measurement (https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.heart_rate_measurement.xml) which supports the idea that it's simply not present on this device.

My information here is weak at best so if you have knowledge otherwise please let me know and we can debug this together!

If you have Visual Studio you can run it with the debugger attached and it outputs more verbose information into VS's debug logs. I'm marking this case as closed for the time being, but I will gladly reopen it if you have more information, or help you debug any issues otherwise.

**Comment by rhymak** [comment]
Thanks for such a quick reply!
A370 is not standalone HR sensor, that's true, but it comes with a
possibility to rebroadcast HR data using BLE (mention:
https://www.polar.com/blog/three-ways-to-use-polar-a370-as-a-heart-rate-sensor/
).
As I said, I managed to get it working with pc which has BT built-in, but
not when using USB dongle (receiver) - screenshot attached.
So I suppose there is just some problem with drivers/recognizing the device
incorrectly or something similar.
I'd gladly provide more information if you're willing to look into this
more, it should help me a lot.

Thanks,
Martin
